### ISSUE TITLE
Allow default classes config

### ISSUE THREAD

**Issue by mattsbanner** [blade-ui-kit/blade-heroicons#17]
I have a default set of custom icons in `config/blade-icons.php` and this package installed.

I would like to define a default height and width for Hero Icons (e.g. `h-5 w-5`). Adding this to the `class` config option of `config/blade-icons.php` also affects my custom set.

Is there/ could there be a way to define default classes specifically for this set? Seems I can't override the `heroicon` config set to add it there.

At the moment, the only solution seems to be defining the classes (`<x-heroicon-o-home class="w-5 h-5"/>`) for every icon individually.

**Comment by mattsbanner** [comment]
Awesome, thanks @driesvints 😄

**Comment by driesvints** [comment]
Released this as v1.2.0
