### ISSUE TITLE
Control SVG Stroke Width

### ISSUE THREAD

**Issue by adamjgriffith** [blade-ui-kit/blade-heroicons#20]
Is there a way to control the stroke-width property using this library?

I have tried something like `<x-heroicon-o-exclamation-circle class="h-12 w-12 stroke-1" />` but I cannot get it to work!

Links:
General: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width
Tailwind: https://tailwindcss.com/docs/stroke-width

**Comment by driesvints** [comment]
Unfortunately not through this library. Icons will need to be optimized to allow for that CSS property. We don't dictate how SVG icons are built. If there's a specific icon library you'd like to use this with, consider asking the authors of the library to provide support for it.

**Comment by adamjgriffith** [comment]
Ok thank you, I will considering opening a similar issue on the [heroicons](https://github.com/tailwindlabs/heroicons) GitHub.

**Comment by victorybiz** [comment]
@driesvints You can override or change the SVG stroke width CSS

```css
/* 
resources/css/app.css 
*/

svg path {
    @apply stroke-1;
 }
```
