### ISSUE TITLE
Unable to locate a class or view for component with orchestra/testbench-dusk

### ISSUE THREAD

**Issue by royduin** [blade-ui-kit/blade-heroicons#23]
See: https://github.com/rapidez/core/actions/runs/986308235 in the artifacts file there are screenshots with:

![image](https://user-images.githubusercontent.com/1703233/123970765-b4c63d80-d9b9-11eb-8db6-ec0b1f7d313f.png)

Any suggestions?

**Comment by driesvints** [comment]
I'll need a lot more info... Can you please point out to the Blade views where the icon is used? Is the project where this is happening open source? How do I reproduce this?

**Comment by royduin** [comment]
It's used [here](https://github.com/rapidez/core/blob/c82bdfb9293192ff47bda14a6e29251d98aeaaaf/resources/views/product/partials/images.blade.php#L51) and yes the whole project is open source. To reproduce; pull, composer install and follow the [browser test steps](https://github.com/rapidez/core#browser-tests) just like the [Github action](https://github.com/rapidez/core/blob/c82bdfb9293192ff47bda14a6e29251d98aeaaaf/.github/workflows/dusk.yml#L52:L62).

**Comment by driesvints** [comment]
I don't see anything special in your project that could be causing it. Sometimes this can be resolved by applying icon caching. Can you try to add that step after the composer install step? https://github.com/blade-ui-kit/blade-icons#caching

**Comment by royduin** [comment]
Needed to register the packages: https://github.com/rapidez/core/commit/fe7dfc9a097ac806eeaea316f132a9d7a57654e8, thanks for your time!
