### ISSUE TITLE
Heroicons 2.0

### ISSUE THREAD

**Issue by martin-ro** [blade-ui-kit/blade-heroicons#27]
[Heroicons 2.0 was published a few hours ago](https://twitter.com/steveschoger/status/1562117153591107586?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1562117153591107586%7Ctwgr%5E5e5c8b22a412100cf596720a8d21116530bc6fe0%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2Fsteveschoger2Fstatus2F1562117153591107586widget%3DTweet). Are there plans to update the package to support them?

Cheers

**Comment by driesvints** [comment]
Yep, will try to get something out very soon. Thanks!
