### ISSUE TITLE
Error message unable to locate component with WSL2

### ISSUE THREAD

**Issue by thomasdominic** [blade-ui-kit/blade-heroicons#32]
- Library Version: The last
- Laravel Version: 9
- PHP Version: 8.1

### Description:
With sail and WSL2, we have this error message

![image](https://user-images.githubusercontent.com/17202290/202456624-2da6b1b8-cfd8-4bbf-b491-5970f16858b0.png)

### Steps To Reproduce:
We created a repo with only blade-heroicons
Install this repo and run with sail and wsl2
https://github.com/codenco-dev/test-heroicons-wsl2

**Comment by driesvints** [comment]
I don't use Windows or wsl2 myself sorry. If you can come up with a bug fix I'd appreciate a PR.

**Comment by adamz01h** [comment]
I was able to solve this on WSL2 by running the docker compose in the home user folder from WSL2.
![image](https://user-images.githubusercontent.com/11203476/204434890-d574418f-5bee-465e-9731-193d0fe6b0e2.png)

**Comment by thomasdominic** [comment]
I found why I have this message, but not why I have the problem.
The problem is when the blade icon package calculate the svg manifest.

I don't know why, but normally the package must see 849 svg, anf it see the 97 last icons ...
