### ISSUE TITLE
Heroicon O Plus Small Bug

### ISSUE THREAD

**Issue by andrewdwallo** [blade-ui-kit/blade-heroicons#36]
- Library Version: 2.0.10
- Laravel Version: 9.47.0
- PHP Version: 8.0.2

### Description:
When using "group-hover:text-white" for the icon class,... the icon does not turn white but stays the same color.

Using other components with the same steps below, the icon turns white, well except for x-heroicon-o-plus as well, and maybe others not sure yet.

### Steps To Reproduce:

x-heroicon-o-plus-small class="mr-2 h-5 w-5 rtl:ml2 rtl:mr-0 group-hover:text-white group-focus:text-white text-primary-500"

**Comment by driesvints** [comment]
Seems to work properly: https://play.tailwindcss.com/Sc3YgAy74n

Did you apply a parent group? https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state
