### ISSUE TITLE
BUG: Unable to locate a class or view for component

### ISSUE THREAD

**Issue by ajmeireles** [blade-ui-kit/blade-heroicons#38]
- Library Version: 2.1.0
- Laravel Version: 10.4.1
- PHP Version: 8.1.7
- System: MacOS Ventura (13.2.1, 22D68)

### Description:

As I know that if I explained it, no one would believe it, so I decided to record it:
https://www.loom.com/share/74c235a5df1444679f77a2a59c53030a

### Steps To Reproduce:

According to above video:
1. `composer require ...` of the package
2. Try to use any icon.

**Comment by driesvints** [comment]
I just tried the exact same thing on the exact same versions and it worked for me. I have no idea why that's not working for you sorry... can you please try a different support channel?

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
