### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by saeedvaziry** [blade-ui-kit/blade-heroicons#44]
- Library Version: latest
- Laravel Version: latest
- PHP Version: all

### Description:

The library tries to load all of the icons into the memory in the ServiceProvider which causes to increase the memory consumption of the server.

### Steps To Reproduce:

compare the memory usage of a fresh Laravel app with and without having this package installed and autoloaded.

**Comment by driesvints** [comment]
Did you read the docs here and applied config caching? https://github.com/blade-ui-kit/blade-icons#caching

**Comment by saeedvaziry** [comment]
Hmm, somehow I missed that part. gonna take a look at that to see how it improves the memory usage
